version: "3.7"
services:
  vault:
    image: hashicorp/vault:1.16
    container_name: vault
    hostname: vault
    ports:
      - 8200:8200
    volumes:
#      - ./_infrastructure/vault/config.hcl:/vault/config/config.hcl
#      - ./_infrastructure/vault/file:/vault/file:rw
#      - ./_infrastructure/vault/logs:/vault/logs:rw
      - ./_infrastructure/vault/file:/vault/file:rw
      - ./_infrastructure/vault/config:/vault/config:rw
    environment:
      - VAULT_ADDR=http://localhost:8200
    cap_add:
      - IPC_LOCK
    command: server
    restart: always